#!/usr/bin/env python3
"""Generate Module 07 notebooks with 15+ cells each."""

import json
from pathlib import Path

MODULE = Path(__file__).resolve().parents[1] / "07_traing_problem_and soultion"
COLAB_BASE = "https://colab.research.google.com/github/Gaurav14cs17/Multimodal-Deep-Learning/blob/main/07_traing_problem_and%20soultion"


def md(*lines):
    return {"cell_type": "markdown", "metadata": {}, "source": [l + "\n" for l in lines]}


def code(*lines):
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [l + "\n" for l in lines]}


def setup_cell(subfolder):
    return code(
        "# ============================================================",
        "#  Colab Setup (run this cell first if on Google Colab)",
        "# ============================================================",
        "import os, sys",
        "",
        "if 'google.colab' in sys.modules:",
        "    !git clone https://github.com/Gaurav14cs17/Multimodal-Deep-Learning.git",
        "    os.chdir('Multimodal-Deep-Learning')",
        f"    os.chdir('07_traing_problem_and soultion/{subfolder}')",
        "    !pip install -q torch torchvision matplotlib numpy",
        "else:",
        "    nb_dir = os.getcwd()",
        "    if not os.path.basename(nb_dir) == '" + subfolder.split("/")[-1] + "':",
        f"        os.chdir(os.path.join(os.path.dirname(os.path.abspath('__file__')), '..', '..', '{subfolder}'))",
        "    sys.path.append(os.path.join(os.getcwd(), '..', '..'))",
        "",
        "print(f'Working directory: {os.getcwd()}')",
    )


def imports_cell():
    return code(
        "import torch",
        "import torch.nn as nn",
        "import torch.nn.functional as F",
        "import numpy as np",
        "import matplotlib.pyplot as plt",
        "",
        "torch.manual_seed(42)",
        "np.random.seed(42)",
        "plt.rcParams.update({'figure.figsize': (10, 5), 'font.size': 11})",
    )


def title_cell(colab_path, title, subtitle=""):
    lines = [
        f"[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)]({COLAB_BASE}/{colab_path})",
        "",
        f"# {title}",
        "",
    ]
    if subtitle:
        lines.append(subtitle)
        lines.append("")
    lines.append("---")
    return md(*lines)


def refs_cell(papers, blogs=None):
    lines = ["## References & Further Reading", ""]
    for p in papers:
        lines.append(f"- {p}")
    if blogs:
        lines.append("")
        lines.append("**Blog posts:**")
        for b in blogs:
            lines.append(f"- {b}")
    return md(*lines)


def save(name, cells):
    nb = {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.10.0"},
        },
        "cells": cells,
    }
    path = MODULE / name
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        json.dump(nb, f, indent=2)
    print(f"Wrote {path} ({len(cells)} cells)")


def nb01_gradient_problems():
    sf = "01_gradient_problems"
    cells = [
        title_cell(f"{sf}/01_gradient_problems.ipynb", "01. Gradient Problems — Vanishing & Exploding Gradients",
                   "Full chain-rule analysis, numerical traces, and PyTorch fixes."),
        setup_cell(sf),
        imports_cell(),
        md(
            "## 1. Why Gradients Fail — The Chain Rule Through $L$ Layers",
            "",
            "For a network $h_0 \\to h_1 \\to \\cdots \\to h_L$ with loss $\\mathcal{L}$:",
            "",
            "$$",
            "\\frac{\\partial \\mathcal{L}}{\\partial W_1} = \\left(\\prod_{l=1}^{L} \\frac{\\partial h_l}{\\partial h_{l-1}}\\right) \\frac{\\partial \\mathcal{L}}{\\partial h_L}",
            "$$",
            "",
            "Each Jacobian $J_l = \\frac{\\partial h_l}{\\partial h_{l-1}}$ multiplies into the product. If $\\lVert J_l \\rVert < 1$ repeatedly → **vanishing**. If $\\lVert J_l \\rVert > 1$ → **exploding**.",
            "",
            "```",
            "Layer:   h0 --> h1 --> h2 --> ... --> hL --> L",
            "Grad:    dL/dh0 <-- dL/dh1 <-- ... <-- dL/dhL",
            "         product of L Jacobians (exponential scaling!)",
            "```",
        ),
        md(
            "### Numerical Example: 10 Layers, $\\lVert J_l \\rVert = 0.5$",
            "",
            "| Layer $l$ | $\\lVert \\partial \\mathcal{L}/\\partial h_l \\rVert$ | Cumulative product |",
            "|-----------|-------------------------------------|-------------------|",
            "| 10 | 1.0 | 1.0 |",
            "| 9 | 0.5 | 0.5 |",
            "| 8 | 0.25 | 0.25 |",
            "| ... | ... | ... |",
            "| 1 | $0.5^9 \\approx 0.002$ | **vanishing** |",
            "",
            "With $\\lVert J_l \\rVert = 1.2$: Layer 1 gradient $\\approx 1.2^9 \\approx 5.16$ → **exploding**.",
        ),
        code(
            "# Simulate gradient norm propagation through L layers",
            "L = 10",
            "norms_contract = [0.5 ** (L - l) for l in range(1, L + 1)]",
            "norms_expand = [1.2 ** (L - l) for l in range(1, L + 1)]",
            "",
            "fig, axes = plt.subplots(1, 2, figsize=(12, 4))",
            "axes[0].bar(range(1, L+1), norms_contract, color='steelblue')",
            "axes[0].set_title('Vanishing: ||J||=0.5 per layer')",
            "axes[0].set_xlabel('Layer'); axes[0].set_ylabel('||grad|| (relative)')",
            "axes[1].bar(range(1, L+1), norms_expand, color='coral')",
            "axes[1].set_title('Exploding: ||J||=1.2 per layer')",
            "axes[1].set_xlabel('Layer')",
            "plt.tight_layout(); plt.show()",
        ),
        md(
            "## 2. Solution: Gradient Clipping",
            "",
            "$$",
            "g \\leftarrow g \\cdot \\frac{\\text{max\\_norm}}{\\max(\\lVert g \\rVert, \\text{max\\_norm})}",
            "$$",
            "",
            "If $\\lVert g \\rVert > \\text{max\\_norm}$, scale down; otherwise unchanged. Preserves direction, caps magnitude.",
        ),
        code(
            "def clip_grad_norm_manual(grad, max_norm=1.0):",
            "    norm = grad.norm()",
            "    if norm > max_norm:",
            "        return grad * (max_norm / norm)",
            "    return grad",
            "",
            "g = torch.tensor([3.0, 4.0])  # ||g|| = 5",
            "g_clipped = clip_grad_norm_manual(g, max_norm=1.0)",
            "print(f'Original ||g||={g.norm():.2f}, clipped ||g||={g_clipped.norm():.4f}')",
            "print(f'Clipped vector: {g_clipped.tolist()}')",
        ),
        md(
            "## 3. Solution: Residual Connections",
            "",
            "$$",
            "h_l = F(h_{l-1}) + h_{l-1}",
            "$$",
            "",
            "**Gradient flow proof:**",
            "",
            "$$",
            "\\frac{\\partial h_L}{\\partial h_l} = \\frac{\\partial h_L}{\\partial h_{l+1}}\\left(I + \\frac{\\partial F(h_l)}{\\partial h_l}\\right)",
            "$$",
            "",
            "The identity term $I$ provides a **direct path** for gradients — even if $\\partial F/\\partial h_l \\approx 0$, gradients can flow via the skip connection.",
        ),
        code(
            "class PlainDeepNet(nn.Module):",
            "    def __init__(self, depth=10, dim=32):",
            "        super().__init__()",
            "        self.layers = nn.ModuleList([",
            "            nn.Sequential(nn.Linear(dim, dim), nn.Tanh()) for _ in range(depth)",
            "        ])",
            "        self.head = nn.Linear(dim, 1)",
            "",
            "    def forward(self, x):",
            "        for layer in self.layers:",
            "            x = layer(x)",
            "        return self.head(x).squeeze(-1)",
            "",
            "class ResidualDeepNet(nn.Module):",
            "    def __init__(self, depth=10, dim=32):",
            "        super().__init__()",
            "        self.layers = nn.ModuleList([",
            "            nn.Sequential(nn.Linear(dim, dim), nn.Tanh()) for _ in range(depth)",
            "        ])",
            "        self.head = nn.Linear(dim, 1)",
            "",
            "    def forward(self, x):",
            "        for layer in self.layers:",
            "            x = x + layer(x)",
            "        return self.head(x).squeeze(-1)",
            "",
            "def grad_norms(model, x, y):",
            "    model.zero_grad()",
            "    loss = F.mse_loss(model(x), y)",
            "    loss.backward()",
            "    norms = []",
            "    for layer in model.layers:",
            "        norms.append(layer[0].weight.grad.norm().item())",
            "    return norms",
            "",
            "x = torch.randn(16, 32); y = torch.randn(16)",
            "plain = PlainDeepNet(); res = ResidualDeepNet()",
            "n_plain = grad_norms(plain, x, y)",
            "n_res = grad_norms(res, x, y)",
            "",
            "plt.plot(range(1, 11), n_plain, 'o-', label='Plain (vanishing)'); plt.plot(range(1, 11), n_res, 's-', label='Residual')",
            "plt.xlabel('Layer'); plt.ylabel('Grad norm'); plt.legend(); plt.title('Gradient Norms: Plain vs Residual'); plt.show()",
        ),
        md(
            "## 4. Layer Normalization",
            "",
            "$$",
            "\\text{LN}(x) = \\gamma \\odot \\frac{x - \\mu}{\\sqrt{\\sigma^2 + \\epsilon}} + \\beta",
            "$$",
            "",
            "Normalizes activations per sample → stabilizes Jacobian singular values, reducing internal covariate shift.",
        ),
        md(
            "## 5. Proper Initialization — Xavier & He",
            "",
            "**Xavier (Glorot):** $\\text{Var}(W) = \\frac{2}{n_{in} + n_{out}}$ for tanh/sigmoid.",
            "",
            "**He (Kaiming):** $\\text{Var}(W) = \\frac{2}{n_{in}}$ for ReLU (accounts for halving variance through ReLU).",
            "",
            "PyTorch: `nn.init.xavier_uniform_`, `nn.init.kaiming_normal_(..., nonlinearity='relu')`.",
        ),
        code(
            "def compare_inits(n_in=256, n_out=256, n_trials=100):",
            "    results = {}",
            "    for name, init_fn in [('Xavier', lambda w: nn.init.xavier_uniform_(w)),",
            "                          ('Default', lambda w: None),",
            "                          ('He', lambda w: nn.init.kaiming_normal_(w, nonlinearity='relu'))]:",
            "        vars_ = []",
            "        for _ in range(n_trials):",
            "            w = torch.empty(n_in, n_out)",
            "            if name != 'Default': init_fn(w)",
            "            x = torch.randn(64, n_in)",
            "            h = F.relu(x @ w)",
            "            vars_.append(h.var().item())",
            "        results[name] = np.mean(vars_)",
            "    return results",
            "",
            "r = compare_inits()",
            "plt.bar(r.keys(), r.values()); plt.ylabel('Mean activation variance'); plt.title('Init schemes'); plt.show()",
        ),
        md(
            "## 6. Mixed Precision — Gradient Scaling",
            "",
            "FP16 gradients can underflow to zero. **Loss scaling:** multiply loss by $S$, backprop, then unscale gradients before optimizer step.",
            "",
            "```",
            "loss_scaled = loss * scale",
            "loss_scaled.backward()",
            "grads = grads / scale  # restore magnitude",
            "```",
        ),
        code(
            "# Demonstrate FP16 underflow without scaling",
            "small_grad = torch.tensor(1e-8, dtype=torch.float16)",
            "print(f'FP16 grad stored as: {small_grad.item()} (underflow to 0!)')",
            "scale = 1024.0",
            "scaled = (torch.tensor(1e-8) * scale).float()",
            "print(f'With loss scaling x{scale:.0f}: effective grad = {scaled.item():.2e}')",
        ),
        md(
            "## 7. Decision Table — When to Use Each Solution",
            "",
            "| Symptom | Likely Cause | Fix | Priority |",
            "|---------|--------------|-----|----------|",
            "| Early layers grad ≈ 0 | Vanishing | Residual + He init + LN | High |",
            "| Loss spikes, grad > 100 | Exploding | Clip grad (max_norm=1.0) | Immediate |",
            "| Activations drift over epochs | Internal covariate shift | LayerNorm / BatchNorm | Medium |",
            "| FP16 training, no updates | Grad underflow | Loss scaling (AMP) | High |",
            "| Very deep MLP/RNN | Product of Jacobians | Residual + skip connections | High |",
        ),
        md(
            "## 8. End-to-End Demo: 10-Layer Network Before/After Fixes",
        ),
        code(
            "def train_and_track(model, steps=50):",
            "    opt = torch.optim.Adam(model.parameters(), lr=1e-2)",
            "    x = torch.randn(32, 32); y = torch.randn(32)",
            "    history = []",
            "    for _ in range(steps):",
            "        opt.zero_grad()",
            "        loss = F.mse_loss(model(x), y)",
            "        loss.backward()",
            "        gn = sum(p.grad.norm().item() for p in model.parameters() if p.grad is not None)",
            "        history.append(gn)",
            "        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)",
            "        opt.step()",
            "    return history",
            "",
            "h1 = train_and_track(PlainDeepNet())",
            "h2 = train_and_track(ResidualDeepNet())",
            "plt.plot(h1, label='Plain + clipping'); plt.plot(h2, label='Residual + clipping')",
            "plt.xlabel('Step'); plt.ylabel('Total grad norm'); plt.legend(); plt.title('Training stability'); plt.show()",
        ),
        refs_cell([
            "Glorot & Bengio (2010) — Understanding the difficulty of training deep feedforward neural networks — [arXiv:1006.2785](https://arxiv.org/abs/1006.2785)",
            "He et al. (2015) — Delving Deep into Rectifiers — [arXiv:1502.01852](https://arxiv.org/abs/1502.01852)",
            "Ba et al. (2016) — Layer Normalization — [arXiv:1607.06450](https://arxiv.org/abs/1607.06450)",
        ], [
            "[Lilian Weng — Why ResNet Works](https://lilianweng.github.io/posts/2017-06-08-overview/)",
            "[Jay Alammar — Visualizing Learning Rates](https://jalammar.github.io/visualizing-learning-rate/)",
        ]),
    ]
    save(f"{sf}/01_gradient_problems.ipynb", cells)


def nb02_loss_landscape():
    sf = "02_loss_landscape_optimization"
    cells = [
        title_cell(f"{sf}/02_loss_landscape_optimization.ipynb", "02. Loss Landscape, Learning Rate & Optimizers"),
        setup_cell(sf),
        imports_cell(),
        md(
            "## 1. Loss Landscape — Why Training Diverges",
            "",
            "High-dimensional loss surfaces have saddle points (not local minima). **Sharp minima** generalize poorly; **flat minima** generalize better.",
            "",
            "```",
            "        Loss",
            "         |    \\ sharp minimum (bad gen.)",
            "         |     \\___/",
            "         |  ___/   \\___  flat minimum (good gen.)",
            "         |_/             \\___",
            "         +--------------------> weight",
            "```",
        ),
        md(
            "## 2. Learning Rate Too High — Quadratic Proof",
            "",
            "For $\\mathcal{L}(w) = \\frac{\\lambda}{2}w^2$, GD update $w_{t+1} = (1 - \\eta\\lambda) w_t$.",
            "",
            "**Divergence when** $\\lvert 1 - \\eta\\lambda \\rvert > 1$ → $\\eta > 2/\\lambda$.",
            "",
            "**Oscillation when** $\\eta\\lambda > 1$ (sign flips each step).",
        ),
        code(
            "lam = 1.0",
            "w = 1.0",
            "for eta, label in [(0.5, 'stable'), (1.5, 'oscillate'), (3.0, 'diverge')]:",
            "    ws = [1.0]",
            "    for _ in range(20):",
            "        ws.append(ws[-1] * (1 - eta * lam))",
            "    plt.plot(ws, label=f'eta={eta} ({label})')",
            "plt.axhline(0, color='k', lw=0.5); plt.legend(); plt.title('GD on L=0.5*lam*w^2, lam=1'); plt.show()",
        ),
        md(
            "## 3. SGD + Momentum",
            "",
            "$$",
            "v_t = \\beta v_{t-1} + g_t, \\quad w_t = w_{t-1} - \\eta v_t",
            "$$",
            "",
            "Effective learning rate increases in consistent gradient directions; dampens oscillations in ravines.",
        ),
        md(
            "## 4. Adam — Bias Correction Proof",
            "",
            "$$",
            "m_t = \\beta_1 m_{t-1} + (1-\\beta_1)g_t, \\quad v_t = \\beta_2 v_{t-1} + (1-\\beta_2)g_t^2",
            "$$",
            "",
            "$$",
            "\\hat{m}_t = \\frac{m_t}{1 - \\beta_1^t}, \\quad \\hat{v}_t = \\frac{v_t}{1 - \\beta_2^t}",
            "$$",
            "",
            "**Why:** $E[m_t] = (1-\\beta_1^t) E[g_t]$ at initialization → dividing removes bias toward zero.",
        ),
        code(
            "def adam_bias_correction(beta1=0.9, steps=10):",
            "    m, g = 0.0, 1.0  # constant gradient",
            "    raw, corrected = [], []",
            "    for t in range(1, steps+1):",
            "        m = beta1 * m + (1 - beta1) * g",
            "        raw.append(m)",
            "        corrected.append(m / (1 - beta1**t))",
            "    return raw, corrected",
            "",
            "raw, corr = adam_bias_correction()",
            "plt.plot(raw, 'o-', label='Raw m_t'); plt.plot(corr, 's-', label='Bias-corrected m_hat')",
            "plt.axhline(1.0, ls='--', color='gray', label='True E[g]'); plt.legend(); plt.title('Adam bias correction'); plt.show()",
        ),
        md(
            "## 5. AdamW vs Adam — Weight Decay $\\neq$ L2",
            "",
            "Adam + L2 adds $\\lambda w$ to the **gradient** (coupled with adaptive rates). AdamW decouples:",
            "",
            "$$",
            "w_t \\leftarrow w_{t-1} - \\eta\\left(\\frac{\\hat{m}_t}{\\sqrt{\\hat{v}_t}+\\epsilon} + \\lambda w_{t-1}\\right)",
            "$$",
            "",
            "Loshchilov & Hutter show AdamW generalizes better than Adam + L2.",
        ),
        md(
            "## 6. LR Schedulers",
            "",
            "**Cosine annealing:** $\\eta_t = \\eta_{min} + \\frac{1}{2}(\\eta_{max} - \\eta_{min})(1 + \\cos(\\pi t / T))$",
            "",
            "**Warmup + cosine:** linear ramp 0 → $\\eta_{max}$ for $W$ steps, then cosine decay.",
        ),
        code(
            "T, W, eta_max, eta_min = 100, 10, 1e-2, 1e-5",
            "lrs = []",
            "for t in range(T):",
            "    if t < W:",
            "        lr = eta_max * t / W",
            "    else:",
            "        prog = (t - W) / (T - W)",
            "        lr = eta_min + 0.5 * (eta_max - eta_min) * (1 + np.cos(np.pi * prog))",
            "    lrs.append(lr)",
            "plt.plot(lrs); plt.xlabel('Step'); plt.ylabel('LR'); plt.title('Warmup + Cosine Annealing'); plt.show()",
        ),
        md(
            "## 7. Compare SGD, Adam, AdamW on Same Problem",
        ),
        code(
            "class TinyMLP(nn.Module):",
            "    def __init__(self):",
            "        super().__init__()",
            "        self.net = nn.Sequential(nn.Linear(10, 64), nn.ReLU(), nn.Linear(64, 1))",
            "    def forward(self, x): return self.net(x).squeeze(-1)",
            "",
            "def train_opt(opt_name, lr=1e-2, wd=0.01, steps=100):",
            "    torch.manual_seed(0)",
            "    model = TinyMLP()",
            "    x = torch.randn(64, 10); y = torch.randn(64)",
            "    if opt_name == 'SGD':",
            "        opt = torch.optim.SGD(model.parameters(), lr=lr, momentum=0.9, weight_decay=wd)",
            "    elif opt_name == 'Adam':",
            "        opt = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=wd)",
            "    else:",
            "        opt = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=wd)",
            "    losses = []",
            "    for _ in range(steps):",
            "        opt.zero_grad()",
            "        loss = F.mse_loss(model(x), y)",
            "        loss.backward(); opt.step()",
            "        losses.append(loss.item())",
            "    return losses",
            "",
            "for name in ['SGD', 'Adam', 'AdamW']:",
            "    plt.plot(train_opt(name), label=name)",
            "plt.xlabel('Step'); plt.ylabel('Loss'); plt.legend(); plt.title('Optimizer comparison'); plt.yscale('log'); plt.show()",
        ),
        md(
            "## 8. Scheduler Decision Table",
            "",
            "| Scheduler | Formula | When to Use |",
            "|-----------|---------|-------------|",
            "| Step decay | $\\eta \\times \\gamma$ every $K$ epochs | Classic CV baselines |",
            "| Cosine | smooth decay to $\\eta_{min}$ | Transformers, CLIP |",
            "| Warmup+cosine | linear warmup then cosine | Large models, Adam |",
            "| One-cycle | ramp up then down | Fast convergence (Smith 2017) |",
        ),
        refs_cell([
            "Kingma & Ba (2015) — Adam — [arXiv:1412.6980](https://arxiv.org/abs/1412.6980)",
            "Loshchilov & Hutter (2019) — Decoupled Weight Decay (AdamW) — [arXiv:1711.05101](https://arxiv.org/abs/1711.05101)",
            "Smith (2017) — Cyclical Learning Rates — [arXiv:1506.01186](https://arxiv.org/abs/1506.01186)",
        ], ["[Lilian Weng — LR Schedules](https://lilianweng.github.io/posts/2021-12-05-large-batch/)"]),
    ]
    save(f"{sf}/02_loss_landscape_optimization.ipynb", cells)


def nb03_overfitting():
    sf = "03_overfitting_underfitting"
    cells = [
        title_cell(f"{sf}/03_overfitting_underfitting.ipynb", "03. Overfitting, Underfitting & Regularization"),
        setup_cell(sf),
        imports_cell(),
        md(
            "## 1. Diagnosing — Four Scenarios",
            "",
            "```",
            "Scenario 1: Good fit     train ↓  val ↓  (both decrease)",
            "Scenario 2: Overfit        train ↓  val ↑  (gap widens)",
            "Scenario 3: Underfit       train ↑  val ↑  (both high)",
            "Scenario 4: Double descent val has second dip after interpolation",
            "```",
        ),
        md(
            "## 2. Bias-Variance Decomposition",
            "",
            "$$",
            "\\mathbb{E}[(y - \\hat{f})^2] = \\text{Bias}^2 + \\text{Variance} + \\text{Noise}",
            "$$",
            "",
            "Overfitting = high variance. Underfitting = high bias.",
        ),
        md(
            "## 3. Dropout — Expected Value Preservation",
            "",
            "$$",
            "\\tilde{h} = h \\odot m / (1-p), \\quad m \\sim \\text{Bernoulli}(1-p)",
            "$$",
            "",
            "$E[\\tilde{h}] = h \\cdot (1-p) \\cdot \\frac{1}{1-p} = h$ — inference uses all units scaled by $(1-p)$.",
        ),
        code(
            "p = 0.5",
            "h = torch.ones(1000, 64)",
            "drops = [F.dropout(h, p=p, training=True).mean().item() for _ in range(200)]",
            "print(f'E[h]={h.mean():.3f}, E[dropout(h)]={np.mean(drops):.3f} (preserved)')",
        ),
        md(
            "## 4. Weight Decay / L2",
            "",
            "$$",
            "\\mathcal{L}_{reg} = \\mathcal{L} + \\frac{\\lambda}{2}\\lVert W \\rVert^2",
            "$$",
            "",
            "Gradient update: $W \\leftarrow (1 - \\eta\\lambda)W - \\eta\\nabla\\mathcal{L}$ — explicit shrinkage each step.",
        ),
        md(
            "## 5. Label Smoothing",
            "",
            "$$",
            "y_{smooth} = (1-\\epsilon) y + \\epsilon / K",
            "$$",
            "",
            "Prevents overconfident logits; softens cross-entropy targets.",
        ),
        md(
            "## 6. Mixup",
            "",
            "$$",
            "\\tilde{x} = \\lambda x_i + (1-\\lambda)x_j, \\quad \\lambda \\sim \\text{Beta}(\\alpha, \\alpha)",
            "$$",
            "",
            "Linearly interpolates inputs and labels → smoother decision boundaries (Zhang et al. 2018).",
        ),
        code(
            "class OverfitNet(nn.Module):",
            "    def __init__(self, hidden=128, dropout=0.0):",
            "        super().__init__()",
            "        self.net = nn.Sequential(",
            "            nn.Linear(2, hidden), nn.ReLU(),",
            "            nn.Dropout(dropout),",
            "            nn.Linear(hidden, hidden), nn.ReLU(),",
            "            nn.Linear(hidden, 2))",
            "    def forward(self, x): return self.net(x)",
            "",
            "def make_data(n=30):",
            "    X = torch.randn(n, 2); y = (X[:, 0] + X[:, 1] > 0).long()",
            "    return X, y",
            "",
            "def train_model(dropout=0.0, wd=0.0, steps=300):",
            "    X, y = make_data()",
            "    model = OverfitNet(dropout=dropout)",
            "    opt = torch.optim.Adam(model.parameters(), lr=1e-2, weight_decay=wd)",
            "    train_loss, val_loss = [], []",
            "    for step in range(steps):",
            "        model.train(); opt.zero_grad()",
            "        loss = F.cross_entropy(model(X), y)",
            "        loss.backward(); opt.step()",
            "        train_loss.append(loss.item())",
            "        model.eval()",
            "        with torch.no_grad():",
            "            vl = F.cross_entropy(model(X + 0.5*torch.randn_like(X)), y).item()",
            "        val_loss.append(vl)",
            "    return train_loss, val_loss",
            "",
            "t0, v0 = train_model()",
            "t1, v1 = train_model(dropout=0.3, wd=0.1)",
            "fig, ax = plt.subplots(1, 2, figsize=(12,4))",
            "ax[0].plot(t0, label='train'); ax[0].plot(v0, label='val'); ax[0].set_title('No regularization'); ax[0].legend()",
            "ax[1].plot(t1, label='train'); ax[1].plot(v1, label='val'); ax[1].set_title('Dropout + weight decay'); ax[1].legend()",
            "plt.show()",
        ),
        md(
            "## 7. Double Descent",
            "",
            "As model capacity crosses the **interpolation threshold** (can fit training data exactly), test error can **decrease again** — contradicting classical U-shaped bias-variance curve (Nakkiran et al. 2019).",
        ),
        md(
            "## 8. Early Stopping — Implicit Regularization",
            "",
            "Stop when validation loss increases for $P$ consecutive epochs. Equivalent to limiting effective model capacity — prevents overfitting without explicit penalty.",
        ),
        code(
            "# Label smoothing demo",
            "K, eps = 10, 0.1",
            "y_hard = torch.zeros(K); y_hard[3] = 1.0",
            "y_smooth = (1 - eps) * y_hard + eps / K",
            "print('Hard label:', y_hard.tolist())",
            "print('Smoothed: ', [round(v, 3) for v in y_smooth.tolist()])",
        ),
        md(
            "## 9. Solution Decision Table",
            "",
            "| Problem | Solution | When |",
            "|---------|----------|------|",
            "| Overfit | Dropout, WD, augmentation | val > train |",
            "| Underfit | More layers, less reg | both losses high |",
            "| Overconfident | Label smoothing | calibration matters |",
            "| Small data | Mixup, augmentation | limited samples |",
        ),
        refs_cell([
            "Srivastava et al. (2014) — Dropout — [JMLR](https://jmlr.org/papers/v15/srivastava14a.html)",
            "Zhang et al. (2018) — mixup — [arXiv:1710.09412](https://arxiv.org/abs/1710.09412)",
            "Nakkiran et al. (2019) — Deep Double Descent — [arXiv:1912.02292](https://arxiv.org/abs/1912.02292)",
        ]),
    ]
    save(f"{sf}/03_overfitting_underfitting.ipynb", cells)


def nb04_batch_size():
    sf = "04_batch_size_memory"
    cells = [
        title_cell(f"{sf}/04_batch_size_memory.ipynb", "04. Batch Size, Memory & Mixed Precision"),
        setup_cell(sf),
        imports_cell(),
        md(
            "## 1. Batch Size & Gradient Variance",
            "",
            "$$",
            "\\text{Var}[\\nabla \\mathcal{L}_B] = \\frac{\\sigma^2}{B}",
            "$$",
            "",
            "Small batch → high variance → noise helps escape sharp minima. Large batch → low variance → may need LR scaling.",
        ),
        md(
            "## 2. Linear Scaling Rule",
            "",
            "$$",
            "\\eta_{new} = \\eta_{base} \\cdot \\frac{B_{new}}{B_{base}}",
            "$$",
            "",
            "Goyal et al. (2017): when batch 256→8192, scale LR linearly + warmup. Breaks when batch too large without LARS/LAMB.",
        ),
        md(
            "## 3. Gradient Accumulation",
            "",
            "$$",
            "g_{accum} = \\frac{1}{K}\\sum_{k=1}^{K} g_k",
            "$$",
            "",
            "Mathematically equivalent to batch size $B \\times K$ without storing all activations at once.",
        ),
        code(
            "def simulate_batch_variance(Bs, sigma2=1.0, trials=500):",
            "    means = []",
            "    for B in Bs:",
            "        vars_ = [np.var(np.random.randn(B) * np.sqrt(sigma2/B)) for _ in range(trials)]",
            "        means.append(np.mean(vars_))",
            "    return means",
            "",
            "Bs = [1, 4, 16, 64, 256]",
            "plt.plot(Bs, simulate_batch_variance(Bs), 'o-')",
            "plt.xlabel('Batch size B'); plt.ylabel('Var[grad estimate]'); plt.title('Variance ~ 1/B'); plt.xscale('log'); plt.show()",
        ),
        md(
            "## 4. GPU Memory Breakdown",
            "",
            "$$",
            "\\text{GPU\\_Mem} = \\text{Params} + \\text{Optimizer} + \\text{Activations} + \\text{Gradients}",
            "$$",
            "",
            "- Params: $P \\times \\text{bytes}$",
            "- Adam states: $3P$ (params + $m$ + $v$)",
            "- Activations: $\\propto B \\times L \\times d^2$",
        ),
        code(
            "def estimate_memory(P, B, L, d, bytes_per=4, optimizer='adam'):",
            "    params = P * bytes_per",
            "    grads = P * bytes_per",
            "    opt = 3 * P * bytes_per if optimizer == 'adam' else 2 * P * bytes_per",
            "    act = B * L * d * d * bytes_per  # simplified per-layer",
            "    total = params + grads + opt + act",
            "    return {'params_mb': params/1e6, 'grads_mb': grads/1e6, 'opt_mb': opt/1e6, 'act_mb': act/1e6, 'total_mb': total/1e6}",
            "",
            "P = 125_000_000  # ~125M params",
            "est = estimate_memory(P, B=8, L=24, d=1024)",
            "for k, v in est.items(): print(f'{k}: {v:.1f} MB')",
        ),
        md(
            "## 5. Mixed Precision — FP16 vs BF16",
            "",
            "| Format | Exponent | Mantissa | Range |",
            "|--------|----------|----------|-------|",
            "| FP32 | 8 bit | 23 bit | ±3.4e38 |",
            "| FP16 | 5 bit | 10 bit | ±65504 |",
            "| BF16 | 8 bit | 7 bit | ±3.4e38 |",
            "",
            "Loss scaling compensates for FP16 grad underflow.",
        ),
        code(
            "# Gradient accumulation demo",
            "model = nn.Linear(10, 2)",
            "opt = torch.optim.SGD(model.parameters(), lr=0.1)",
            "accum_steps = 4",
            "opt.zero_grad()",
            "for k in range(accum_steps):",
            "    x = torch.randn(8, 10)",
            "    loss = model(x).sum() / accum_steps",
            "    loss.backward()",
            "opt.step()",
            "print('Gradient accumulation: 4 micro-batches of 8 = effective batch 32')",
        ),
        code(
            "# AMP training loop sketch",
            "from torch.cuda.amp import autocast, GradScaler",
            "use_amp = torch.cuda.is_available()",
            "scaler = GradScaler(enabled=use_amp)",
            "model = nn.Linear(10, 2); opt = torch.optim.Adam(model.parameters())",
            "x = torch.randn(16, 10)",
            "opt.zero_grad()",
            "with autocast(enabled=use_amp):",
            "    loss = F.cross_entropy(model(x), torch.randint(0, 2, (16,)))",
            "scaler.scale(loss).backward()",
            "scaler.step(opt); scaler.update()",
            "print(f'AMP step completed (cuda={use_amp})')",
        ),
        md(
            "## 6. Linear Scaling Numerical Example",
            "",
            "Base: $B=256$, $\\eta=0.1$. Scale to $B=2048$ (8×):",
            "",
            "$$",
            "\\eta_{new} = 0.1 \\times \\frac{2048}{256} = 0.8",
            "$$",
            "",
            "With 500-step linear warmup from 0 → 0.8.",
        ),
        code(
            "# Linear scaling rule demo",
            "eta_base, B_base = 0.1, 256",
            "for B_new in [256, 512, 1024, 2048, 8192]:",
            "    eta = eta_base * B_new / B_base",
            "    print(f'B={B_new:5d} -> eta={eta:.3f}')",
        ),
        md(
            "## 7. ZeRO Stages",
            "",
            "| Stage | Sharded | Memory Reduction |",
            "|-------|---------|------------------|",
            "| 0 | Nothing (DDP) | 1× |",
            "| 1 | Optimizer states | ~4× on optimizer |",
            "| 2 | + Gradients | ~8× total |",
            "| 3 | + Parameters | Linear in GPU count |",
        ),
        md(
            "## 8. OOM Solutions",
            "",
            "| Technique | Memory Saved | Compute Cost |",
            "|-----------|---------------|--------------|",
            "| Grad accumulation | Activations ↓ | Same total |",
            "| Checkpointing | $O(L) \\to O(\\sqrt{L})$ | ~33% extra |",
            "| ZeRO Stage 1 | Optimizer sharded | Communication |",
            "| ZeRO Stage 3 | All states sharded | More comm |",
            "| FSDP | Like ZeRO-3 in PyTorch | Built-in |",
        ),
        refs_cell([
            "Goyal et al. (2017) — Accurate, Large Minibatch SGD — [arXiv:1706.02677](https://arxiv.org/abs/1706.02677)",
            "Micikevicius et al. (2018) — Mixed Precision Training — [arXiv:1710.03740](https://arxiv.org/abs/1710.03740)",
            "Rajbhandari et al. (2020) — ZeRO — [arXiv:1910.02054](https://arxiv.org/abs/1910.02054)",
        ]),
    ]
    save(f"{sf}/04_batch_size_memory.ipynb", cells)


def nb05_instability():
    sf = "05_training_instability"
    cells = [
        title_cell(f"{sf}/05_training_instability.ipynb", "05. Training Instability, NaN/Inf & Convergence"),
        setup_cell(sf),
        imports_cell(),
        md(
            "## 1. Why Loss Goes NaN — Root Causes",
            "",
            "```",
            "Loss is NaN?",
            "  ├─ Softmax overflow? (x > 88.7 in FP32)",
            "  ├─ Division by zero in norm?",
            "  ├─ Exploding attention logits?",
            "  ├─ LR too high?",
            "  └─ Bad initialization?",
            "```",
        ),
        md(
            "## 2. Softmax Overflow & Log-Sum-Exp",
            "",
            "$e^{88.7} \\approx 1.6 \\times 10^{38}$ → FP32 overflow.",
            "",
            "**Stable softmax:** subtract $c = \\max(x)$:",
            "",
            "$$",
            "\\log\\sum_i e^{x_i} = c + \\log\\sum_i e^{x_i - c}",
            "$$",
        ),
        code(
            "def naive_softmax(x):",
            "    exp_x = torch.exp(x)",
            "    return exp_x / exp_x.sum()",
            "",
            "def stable_softmax(x):",
            "    c = x.max()",
            "    exp_x = torch.exp(x - c)",
            "    return exp_x / exp_x.sum()",
            "",
            "x = torch.tensor([1000.0, 1001.0, 999.0])",
            "print('Naive:', naive_softmax(x))  # nan",
            "print('Stable:', stable_softmax(x))",
        ),
        md(
            "## 3. Attention Instability",
            "",
            "$$",
            "\\text{Attn} = \\text{softmax}\\left(\\frac{QK^\\top}{\\sqrt{d_k}}\\right)",
            "$$",
            "",
            "If $Q, K$ grow unbounded, logits explode before softmax. **Fix:** Pre-LN, scaled dot-product, lower LR.",
        ),
        md(
            "## 4. Pre-LN vs Post-LN",
            "",
            "**Post-LN:** $x + \\text{Attn}(\\text{LN}(x))$ — gradients through LN can vanish early in training.",
            "",
            "**Pre-LN:** $\\text{LN}(x + \\text{Attn}(x))$ — better gradient norms at initialization (Xiong et al. 2020).",
        ),
        md(
            "## 5. Spectral Normalization",
            "",
            "$$",
            "\\bar{W} = \\frac{W}{\\sigma(W)}",
            "$$",
            "",
            "Constrains Lipschitz constant of linear layer → bounds gradient magnitude.",
        ),
        md(
            "## 6. Multimodal-Specific: CLIP Temperature Collapse",
            "",
            "When learnable $\\tau \\to 0$, similarities are divided by tiny $\\tau$ → logits $\\to \\pm\\infty$.",
            "",
            "**Fix:** clamp $\\tau \\geq \\tau_{min}$ (e.g. 0.01) or use fixed $\\tau = 0.07$.",
        ),
        code(
            "def clip_loss(similarities, tau):",
            "    logits = similarities / tau",
            "    labels = torch.arange(similarities.size(0))",
            "    return F.cross_entropy(logits, labels)",
            "",
            "S = torch.randn(4, 4) * 0.5",
            "for tau in [0.07, 0.001, 0.0001]:",
            "    loss = clip_loss(S, tau)",
            "    print(f'tau={tau}: loss={loss.item():.4f}')",
        ),
        code(
            "# Gradient monitor — detect instability before NaN",
            "class GradMonitor:",
            "    def __init__(self, threshold=100.0):",
            "        self.threshold = threshold",
            "    def check(self, model):",
            "        total = 0.0",
            "        for p in model.parameters():",
            "            if p.grad is not None:",
            "                total += p.grad.norm().item() ** 2",
            "        total = total ** 0.5",
            "        if total > self.threshold or np.isnan(total):",
            "            print(f'WARNING: grad norm = {total}')",
            "        return total",
            "",
            "m = nn.Linear(10, 10)",
            "x = torch.randn(4, 10) * 100  # large input -> potential instability",
            "m(x).sum().backward()",
            "GradMonitor(threshold=50).check(m)",
        ),
        md(
            "## 7. Modality Collapse",
            "",
            "One encoder receives all gradient signal; other modality ignored. **Mitigation:** balanced loss weights, gradient clipping per tower, stop-gradient on dominant branch.",
        ),
        md(
            "## 8. muP — Width-Independent Hyperparameters",
            "",
            "Scale learning rate and initialization with width so optimal $\\eta$ does not change when model width increases (Yang et al. 2022). Critical for scaling law experiments.",
        ),
        code(
            "# Reproduce softmax overflow then fix with log-sum-exp loss",
            "def log_softmax_stable(x):",
            "    c = x.max(dim=-1, keepdim=True).values",
            "    return x - c - torch.log(torch.exp(x - c).sum(dim=-1, keepdim=True))",
            "",
            "logits = torch.tensor([[1000., 1001., 999.]])",
            "print('Stable log-softmax:', log_softmax_stable(logits))",
        ),
        md(
            "## 9. Instability Fix Decision Table",
            "",
            "| Issue | Fix | Priority |",
            "|-------|-----|----------|",
            "| Softmax NaN | Log-sum-exp | Immediate |",
            "| Transformer NaN | Pre-LN | High |",
            "| CLIP NaN | Clamp tau | High |",
            "| Grad spikes | Monitor + clip | Preventive |",
        ),
        refs_cell([
            "Xiong et al. (2020) — On Layer Normalization in Transformers — [arXiv:2002.04745](https://arxiv.org/abs/2002.04745)",
            "Yang et al. (2022) — Tensor Programs V (μP) — [arXiv:2203.03466](https://arxiv.org/abs/2203.03466)",
            "Miyato et al. (2018) — Spectral Normalization — [arXiv:1802.05957](https://arxiv.org/abs/1802.05957)",
        ]),
    ]
    save(f"{sf}/05_training_instability.ipynb", cells)


def nb06_distributed():
    sf = "06_distributed_training"
    cells = [
        title_cell(f"{sf}/06_distributed_training.ipynb", "06. Distributed Training — DDP, FSDP & Parallelism"),
        setup_cell(sf),
        imports_cell(),
        md(
            "## 1. Why Distributed?",
            "",
            "$$",
            "T \\propto \\frac{N_{steps} \\cdot B_{local}}{G}",
            "$$",
            "",
            "$G$ = number of GPUs. Ideal speedup linear in $G$; communication adds overhead.",
        ),
        md(
            "## 2. Data Parallel — AllReduce",
            "",
            "$$",
            "g = \\frac{1}{G}\\sum_{g=1}^{G} g_g",
            "$$",
            "",
            "Each GPU computes gradients on local batch; AllReduce averages them.",
            "",
            "```",
            "GPU0: g0 ──┐",
            "GPU1: g1 ──┼── AllReduce ──> g = mean(g0,g1,...)",
            "GPU2: g2 ──┘",
            "```",
        ),
        md(
            "## 3. Ring AllReduce Bandwidth",
            "",
            "$$",
            "\\text{Data moved} = \\frac{2(G-1)}{G} \\cdot P \\cdot \\text{bytes}",
            "$$",
            "",
            "For $G=8$, factor $\\approx 1.75$ — nearly optimal bandwidth utilization.",
        ),
        md(
            "## 4. Model Parallelism",
            "",
            "**Tensor parallel:** split $W$ across GPUs: $Y = X[W_1 \\| W_2]$",
            "",
            "**Pipeline parallel:** micro-batches reduce bubble ratio:",
            "",
            "$$",
            "\\text{bubble} = \\frac{G-1}{G-1+M}",
            "$$",
            "",
            "$M$ = number of micro-batches.",
        ),
        code(
            "def ring_allreduce_bytes(P, G, bytes_per=4):",
            "    return 2 * (G - 1) / G * P * bytes_per",
            "",
            "P = 7_000_000_000  # 7B params",
            "for G in [2, 4, 8, 64]:",
            "    gb = ring_allreduce_bytes(P, G) / 1e9",
            "    print(f'G={G:2d}: AllReduce comm per step ≈ {gb:.2f} GB')",
        ),
        md(
            "## 5. Practical Recipes",
            "",
            "| GPUs | Recipe |",
            "|------|--------|",
            "| 1 | AMP + gradient checkpointing |",
            "| 2–8 | DDP or FSDP |",
            "| 8–64 | FSDP + tensor parallel |",
            "| 64+ | 3D parallel (data + tensor + pipeline) |",
        ),
        code(
            "# DDP skeleton (runs on CPU for demo; use cuda + init_process_group in production)",
            "import torch.nn as nn",
            "from torch.nn.parallel import DistributedDataParallel as DDP",
            "",
            "model = nn.Linear(10, 2)",
            "print('DDP wraps model; each rank gets local batch, gradients AllReduced')",
            "print('FSDP shards params + optimizer states across ranks (PyTorch 2.x)')",
            "",
            "# Effective global batch",
            "local_B, world_size = 8, 4",
            "global_B = local_B * world_size",
            "print(f'local_B={local_B}, world_size={world_size} -> global_B={global_B}')",
        ),
        code(
            "# Communication vs compute tradeoff",
            "compute_ms = 200  # forward+backward per step",
            "for G in [1, 2, 4, 8]:",
            "    P = 1e9",
            "    comm_ms = ring_allreduce_bytes(int(P), G) / 1e9 * 10  # rough: 10ms/GB",
            "    eff = compute_ms / (compute_ms/G + comm_ms) if G > 1 else 1.0",
            "    print(f'G={G}: comm~{comm_ms:.0f}ms, efficiency~{eff:.2f}x')",
        ),
        md(
            "## 6. Pipeline Parallel — Bubble Visualization",
            "",
            "```",
            "Time ->",
            "Stage0: [F0][F1][F2][F3]     (F=forward micro-batch)",
            "Stage1:     [F0][F1][F2][F3]",
            "Stage2:         [F0][F1][F2][F3]",
            "Idle (bubble) at start/end reduced by increasing micro-batches M",
            "```",
        ),
        md(
            "## 7. FSDP vs DDP",
            "",
            "| Feature | DDP | FSDP |",
            "|---------|-----|------|",
            "| Model replication | Full on each GPU | Sharded |",
            "| Memory | Highest | Lowest |",
            "| Communication | AllReduce grads | AllGather params |",
            "| Best for | Fits in VRAM | Large models |",
        ),
        code(
            "# Pipeline bubble ratio",
            "def bubble_ratio(stages, micro_batches):",
            "    return (stages - 1) / (stages - 1 + micro_batches)",
            "",
            "for M in [1, 4, 8, 16]:",
            "    b = bubble_ratio(4, M)",
            "    print(f'Stages=4, M={M:2d}: bubble={b:.1%}')",
        ),
        refs_cell([
            "Li et al. (2020) — PyTorch Distributed — [docs](https://pytorch.org/tutorials/intermediate/ddp_tutorial.html)",
            "Narayanan et al. (2021) — Megatron-LM — [arXiv:2104.04473](https://arxiv.org/abs/2104.04473)",
            "Zhao et al. (2023) — PyTorch FSDP — [PyTorch blog](https://pytorch.org/blog/introducing-pytorch-fully-sharded-data-parallel-api/)",
        ]),
    ]
    save(f"{sf}/06_distributed_training.ipynb", cells)


if __name__ == "__main__":
    nb01_gradient_problems()
    nb02_loss_landscape()
    nb03_overfitting()
    nb04_batch_size()
    nb05_instability()
    nb06_distributed()
    print("Done.")
